version: '3.8'
services:
  db:
    image: postgres:12.11
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    volumes:
      - ./app:/app:cached
    working_dir: /app